# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='EntryTemplateItem',
        ),
        migrations.RenameField(
            model_name='entrytemplateitem',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='agenda',
        ),
    ]
