# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20180922_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryTemplateItem',
            new_name='TemplateItem',
        ),
    ]
