# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('agenda', '0004_entryitem_template_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='label',
        ),
    ]
